apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.0.0
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: prometheus
      timeInterval: "15s"
    editable: false